name: .NET Core Build and Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  backend-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Privoxy and Dependencies
      uses: mstksg/get-package@v1
      with:
        apt-get: privoxy libbrotli-dev libmbedtls-dev
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v2.2.0
      with:
        dotnet-version: '7.0.x'
    - name: Install dependencies
      run: dotnet restore "backend/DvbLive.sln"
    - name: Build
      run: dotnet build "backend/DvbLive.sln" --configuration Release --no-restore
    - name: Test
      run: dotnet test "backend/DvbLive.sln" --configuration Release --collect "Code Coverage" --no-build
      
  backend-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v2.2.0
      with:
        dotnet-version: '7.0.x'
    - name: Install dependencies
      run: dotnet restore "backend/DvbLive.sln"
    - name: Build
      run: dotnet build "backend/DvbLive.sln" --configuration Release --no-restore
    - name: Test
      run: dotnet test "backend/DvbLive.sln" --configuration Release --collect "Code Coverage" --no-build
